apiVersion: 1

# Good Sample
# https://github.com/grafana/grafana/blob/main/devenv/datasources.yaml

deleteDatasources:
  - name: evc-testdata
  - name: evc-redis
  - name: evc-mysql
  - name: evc-prometheus

datasources:

  - name: evc-testdata
    isDefault: true
    type: testdata
    
  - name: evc-redis
    type: redis-datasource
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    url: redis://192.168.1.6:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    
  - name: evc-prometheus
    uid: evc-prometheus
    type: prometheus
    access: proxy
    url: http://192.168.1.6:9090
    basicAuth: true #username: admin, password: admin
    basicAuthUser: admin
    jsonData:
      manageAlerts: true
      alertmanagerUid: gdev-alertmanager
      prometheusType: Prometheus #Cortex | Mimir | Prometheus | Thanos
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: gdev-tempo
    secureJsonData:
      basicAuthPassword: admin
     
  - name: evc-mysql
    type: mysql
    url: 192.168.1.6:3306
    user: dev
    jsonData:
      database: dev
    secureJsonData:
      password: dev
