version: "3.9"

services:
  backend:
    build: ./backend
    container_name: analyzer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - analyzer-net

  frontend:
    build: ./frontend
    container_name: analyzer-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - analyzer-net

networks:
  analyzer-net: